### ISSUE TITLE
新版docker的位置错误

### ISSUE THREAD

**Issue by lumia1998** [lgc-KoiDev/koishi-plugin-memes-api#18]
不止我一个人更新docker的meme api后无法使用了
出现
```
2024-08-18 23:36:24 [E] app TypeError: patterns is not iterable
                            at Object.apply (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:781:29)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Promise.all (index 76)
                            at async Proxy.flush (/koishi/node_modules/@cordisjs/core/lib/index.cjs:501:7)
                            at async Proxy.start (/koishi/node_modules/@cordisjs/core/lib/index.cjs:575:5)
                            at async start (/koishi/node_modules/koishi/lib/worker/index.js:146:3)
2024-08-18 23:36:24 [E] memes-api MemeError: unexpected-error (Error: context disposed)
                            at MemeSource.request (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:377:13)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async MemeSource.renderList (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:385:7)
2024-08-18 23:36:52 [I] loader unload plugin memes-api:mj450v
2024-08-18 23:37:05 [I] loader apply plugin memes-api:ycypdm
2024-08-18 23:37:08 [E] app TypeError: patterns is not iterable
                            at Object.apply (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:781:29)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-18 23:37:08 [E] memes-api MemeError: unexpected-error (Error: context disposed)
                            at MemeSource.request (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:377:13)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async MemeSource.renderList (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:385:7)
2024-08-18 23:37:09 [I] loader unload plugin memes-api:ycypdm
2024-08-18 23:37:10 [I] loader apply plugin memes-api:ycypdm
2024-08-18 23:37:13 [I] memes-api Plugin setup successfully, loaded 228 memes.
2024-08-18 23:37:20 [E] memes-api MemeError: [404] unknown-error [object Object]
                            at MemeSource.request (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:377:13)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async MemeSource.parseArgs (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:415:8)
                            at async /koishi/node_modules/koishi-plugin-memes-api/lib/index.js:663:30
                            at async /koishi/node_modules/koishi-plugin-memes-api/lib/index.js:542:14
                            at async _Command.<anonymous> (/koishi/node_modules/koishi-plugin-memes-api/lib/index.js:738:16)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1078:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1092:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2059:22
                            at async Proxy.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:1968:22)
```

**Comment by lgc2333** [comment]
新版memes-generator改东西了，等我适配

**Comment by lumia1998** [comment]
你是我见过回复最快的开发者

**Comment by WSXYT** [comment]
> 新版meme-generator改东西了，等我适配 最近几天没时间，因为回家了没带电脑

我也这样啦，什么时候有空适配呢qwq

**Comment by lumia1998** [comment]
> > 新版meme-generator改东西了，等我适配 最近几天没时间，因为回家了没带电脑
> 
> 我也这样啦，什么时候有空适配呢qwq

先用旧版的吧不着急人家没开学呢吧

**Comment by WSXYT** [comment]
> > > 新版meme-generator改东西了，等我适配 最近几天没时间，因为回家了没带电脑
> > 
> > 
> > 我也这样啦，什么时候有空适配呢qwq
> 
> 先用旧版的吧不着急人家没开学呢吧

话说怎么用旧版qwq

**Comment by lgc2333** [comment]
> 话说怎么用旧版qwq

用 pip 安装的话，使用

```shell
pip install "meme-generator<0.1"
```

即可

**Comment by lumia1998** [comment]
还没更新吗

**Comment by lgc2333** [comment]
摸鱼ing

**Comment by lumia1998** [comment]
> 摸鱼ing

别摸了哥,memeapi多了好多好玩的等你更新了
