### ISSUE TITLE
注册指令失败

### ISSUE THREAD

**Issue by Logthm** [lgc-KoiDev/koishi-plugin-memes-api#23]
## 问题

启用插件后，提示无法注册指令。

## 环境

```
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.18.0
    Console: 5.29.2
    Koishi Desktop: 1.1.3
```

## 报错日志

```
1000|2024-10-04 15:46:58 [I] loader apply plugin memes-api:g5j5oe
1000|2024-10-04 15:46:59 [W] memes-api Failed to initialize commands, plugin will not work
1000|2024-10-04 15:46:59 [W] memes-api TypeError: Cannot read properties of undefined (reading 'args_type')
1000|                            at registerGenerateOptions (/root/koishi/data/instances/default/node_modules/koishi-plugin-memes-api/lib/index.js:440:33)
1000|                            at /root/koishi/data/instances/default/node_modules/koishi-plugin-memes-api/lib/index.js:523:48
1000|                            at registerGenerateCmd (/root/koishi/data/instances/default/node_modules/koishi-plugin-memes-api/lib/index.js:454:5)
1000|                            at ctx.$.reRegisterGenerateCommands (/root/koishi/data/instances/default/node_modules/koishi-plugin-memes-api/lib/index.js:523:37)
1000|                            at Array.map (<anonymous>)
1000|                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1000|                            at Object.apply (/root/koishi/data/instances/default/node_modules/koishi-plugin-memes-api/lib/index.js:1433:17)
```

**Comment by lgc2333** [comment]
升级meme-generator
