### ISSUE TITLE
报错导致koishi无限重启

### ISSUE THREAD

**Issue by Haku530** [lgc-KoiDev/koishi-plugin-memes-api#25]
`2024-10-12 17:22:38 [W] memes-api Failed to initialize commands, plugin will not work
2024-10-12 17:22:38 [W] memes-api TypeError: Cannot read properties of undefined (reading 'args_type')
                            at registerGenerateOptions (C:\deve\koishi-app\node_modules\koishi-plugin-memes-api\lib\index.js:440:33)
                            at registerGenerateCmd (C:\deve\koishi-app\node_modules\koishi-plugin-memes-api\lib\index.js:454:5)
                            at C:\deve\koishi-app\node_modules\koishi-plugin-memes-api\lib\index.js:523:48
                            at Array.map (<anonymous>)
                            at ctx.$.reRegisterGenerateCommands (C:\deve\koishi-app\node_modules\koishi-plugin-memes-api\lib\index.js:523:37)
                            at Object.apply (C:\deve\koishi-app\node_modules\koishi-plugin-memes-api\lib\index.js:1450:17)
                            at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
                            at async Promise.all (index 40)
                            at async Proxy.flush (C:\deve\koishi-app\node_modules\@cordisjs\core\lib\index.cjs:497:7)
                            at async Proxy.start (C:\deve\koishi-app\node_modules\@cordisjs\core\lib\index.cjs:571:5)
2024-10-12 17:22:38 [E] app TypeError: Cannot read properties of undefined (reading 'name')
                            at CommandManager.ensure (C:\deve\koishi-app\node_modules\@koishijs\plugin-commands\lib\index.js:170:45)
                            at CommandManager.accept (C:\deve\koishi-app\node_modules\@koishijs\plugin-commands\lib\index.js:274:10)
                            at C:\deve\koishi-app\node_modules\@koishijs\plugin-commands\lib\index.js:165:12
                            at Object.apply (C:\deve\koishi-app\node_modules\@cordisjs\core\lib\index.cjs:171:28)
                            at Timeout.<anonymous> (C:\deve\koishi-app\node_modules\@cordisjs\timer\lib\index.cjs:42:9)
                            at listOnTimeout (node:internal/timers:594:17)
                            at process.processTimers (node:internal/timers:529:7)`
求助

**Comment by lgc2333** [comment]
#23
